jspsych-node:
  build: .
  links:
    - mongo
  volumes:
   - ./app:/usr/src/app
  ports:
   - "3000:3000"
  container_name: jspsych-node
mongo:
  image: mongo
rockmongo:
  image: webts/rockmongo
  ports:
   - "8008:80"
  links:
   - mongo:db